---
- hosts: java
  become: yes
  gather_facts: no
  handlers:
    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
  pre_tasks:
    - name: install python
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)
  tasks:
    - name: Gather facts
      setup:
    - name: make java 14 directory
      file:
        path: /usr/lib/java14
        state: directory
    - name: Download Java tarball
      get_url:
        url: https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_linux-x64_bin.tar.gz
        dest: /etc/openjdk-14.0.2_linux-x64_bin.tar.gz
        validate_certs: no
    - name: unpack tarball
      unarchive:
        src: /etc/openjdk-14.0.2_linux-x64_bin.tar.gz
        dest: /usr/lib/java14
        remote_src: yes
    - name: update alternatives for java
      alternatives:
        name: java
        path: /usr/lib/java14/jdk-14.0.2/bin/java
        link: /usr/bin/java
        priority: 20000
#    - name: set JAVA_HOME environment variable
#      blockinfile:
#        insertafter: EOF
#        path: /etc/environment
#        block:
#          export JAVA_HOME=/usr/lib/java14/jdk14.0.2
#    - name: set PATH
#      blockinfile:
#        insertafter: EOF
#        path: /etc/environment
#        block:
#          export PATH=$JAVA_HOME/bin:$PATH
    - name: Copy jar file to target host
      copy:
        src: ./javaWebApp/target/serving-web-content-0.0.1-SNAPSHOT.jar
        dest: /bin/serving-web-content-0.0.1-SNAPSHOT.jar
        owner: root
        group: root
        mode: '0777'
    - name:   create java web app service
      blockinfile:
        create: yes
        insertafter: EOF
        path: /etc/systemd/system/javaWebApp.service
        block: |
          [Unit]
          Description=Java Web App

          [Service]
          WorkingDirectory=/bin
          ExecStart=/usr/lib/java14/jdk-14.0.2/bin/java -jar serving-web-content-0.0.1-SNAPSHOT.jar
          User=root
          Type=simple
          Restart=on-failure
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
    - name: run a systemctl daemon
      systemd:
        daemon_reload: yes
        name: javaWebApp.service
        state: started

